// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'logical/models/data_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1058496472453603985),
      name: 'SettingData',
      lastPropertyId: const IdUid(4, 7262872699300495940),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4117093946599552680),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 9003708541513460382),
            name: 'star1',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7235049586782103387),
            name: 'star2',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7262872699300495940),
            name: 'star3',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 8722639228522268265),
      name: 'Activity',
      lastPropertyId: const IdUid(3, 309017516457092489),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7989334751580241133),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 4373255947179452804),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 309017516457092489),
            name: 'totalTime',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 4553696370115336667),
      name: 'History',
      lastPropertyId: const IdUid(3, 5791785284009579610),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4441731996585464932),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8329120420446825167),
            name: 'date',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 3314748906986269620)),
        ModelProperty(
            id: const IdUid(3, 5791785284009579610),
            name: 'todayTime',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 1477508274139197736),
      lastIndexId: const IdUid(1, 3314748906986269620),
      lastRelationId: const IdUid(1, 4845263384195646647),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [1477508274139197736],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        7913260309329376409,
        3441951625287374042,
        5171683998001060752,
        8084420137536421322
      ],
      retiredRelationUids: const [4845263384195646647],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    SettingData: EntityDefinition<SettingData>(
        model: _entities[0],
        toOneRelations: (SettingData object) => [],
        toManyRelations: (SettingData object) => {},
        getId: (SettingData object) => object.id,
        setId: (SettingData object, int id) {
          object.id = id;
        },
        objectToFB: (SettingData object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.star1);
          fbb.addInt64(2, object.star2);
          fbb.addInt64(3, object.star3);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final star1Param =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final star2Param =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final star3Param =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = SettingData(
              star1: star1Param,
              star2: star2Param,
              star3: star3Param,
              id: idParam);

          return object;
        }),
    Activity: EntityDefinition<Activity>(
        model: _entities[1],
        toOneRelations: (Activity object) => [],
        toManyRelations: (Activity object) => {},
        getId: (Activity object) => object.id,
        setId: (Activity object, int id) {
          object.id = id;
        },
        objectToFB: (Activity object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.totalTime);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final totalTimeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = Activity(nameParam, totalTimeParam, id: idParam);

          return object;
        }),
    History: EntityDefinition<History>(
        model: _entities[2],
        toOneRelations: (History object) => [],
        toManyRelations: (History object) => {},
        getId: (History object) => object.id,
        setId: (History object, int id) {
          object.id = id;
        },
        objectToFB: (History object, fb.Builder fbb) {
          final dateOffset =
              object.date == null ? null : fbb.writeString(object.date!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dateOffset);
          fbb.addInt64(2, object.todayTime);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final todayTimeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = History(dateParam, todayTimeParam, id: idParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [SettingData] entity fields to define ObjectBox queries.
class SettingData_ {
  /// see [SettingData.id]
  static final id =
      QueryIntegerProperty<SettingData>(_entities[0].properties[0]);

  /// see [SettingData.star1]
  static final star1 =
      QueryIntegerProperty<SettingData>(_entities[0].properties[1]);

  /// see [SettingData.star2]
  static final star2 =
      QueryIntegerProperty<SettingData>(_entities[0].properties[2]);

  /// see [SettingData.star3]
  static final star3 =
      QueryIntegerProperty<SettingData>(_entities[0].properties[3]);
}

/// [Activity] entity fields to define ObjectBox queries.
class Activity_ {
  /// see [Activity.id]
  static final id = QueryIntegerProperty<Activity>(_entities[1].properties[0]);

  /// see [Activity.name]
  static final name = QueryStringProperty<Activity>(_entities[1].properties[1]);

  /// see [Activity.totalTime]
  static final totalTime =
      QueryIntegerProperty<Activity>(_entities[1].properties[2]);
}

/// [History] entity fields to define ObjectBox queries.
class History_ {
  /// see [History.id]
  static final id = QueryIntegerProperty<History>(_entities[2].properties[0]);

  /// see [History.date]
  static final date = QueryStringProperty<History>(_entities[2].properties[1]);

  /// see [History.todayTime]
  static final todayTime =
      QueryIntegerProperty<History>(_entities[2].properties[2]);
}
