// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'DB/models/data_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7308131095044400048),
      name: 'Activity',
      lastPropertyId: const obx_int.IdUid(3, 7604896248958337440),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4806168251486484939),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7609100641152165524),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7604896248958337440),
            name: 'timeSpent',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7786140021838116532),
      name: 'FruitUsage',
      lastPropertyId: const obx_int.IdUid(4, 6507040598707643366),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4297232142086647933),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6507040598707643366),
            name: 'usageCount',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 4144517228415667832),
      name: 'Session',
      lastPropertyId: const obx_int.IdUid(5, 1944272196284508478),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 605701392023475632),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6338889813110666157),
            name: 'date',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8205611003461661331),
            name: 'timeSpent',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1944272196284508478),
            name: 'topic',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 1891301343357838477),
      name: 'Setting',
      lastPropertyId: const obx_int.IdUid(9, 1730988259763430046),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8399678696690245671),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2751110199435000839),
            name: 'star1',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3517786977246739871),
            name: 'star2',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6972530011564583542),
            name: 'star3',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1043303583286677354),
            name: 'doneMinutes',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2821781989486638400),
            name: 'hourOfRest',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2175272365520808783),
            name: 'timeOfRest',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 1891301343357838477),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [7609313741310014007],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        4247840349701161003,
        4278223133284466980,
        8161804479967321504,
        265637773826788162,
        5228637705360280213,
        8377744117736287978,
        1730988259763430046,
        588490658857297284,
        4440568647595294747
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Activity: obx_int.EntityDefinition<Activity>(
        model: _entities[0],
        toOneRelations: (Activity object) => [],
        toManyRelations: (Activity object) => {},
        getId: (Activity object) => object.id,
        setId: (Activity object, int id) {
          object.id = id;
        },
        objectToFB: (Activity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.timeSpent);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final timeSpentParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object =
              Activity(id: idParam, name: nameParam, timeSpent: timeSpentParam);

          return object;
        }),
    FruitUsage: obx_int.EntityDefinition<FruitUsage>(
        model: _entities[1],
        toOneRelations: (FruitUsage object) => [],
        toManyRelations: (FruitUsage object) => {},
        getId: (FruitUsage object) => object.id,
        setId: (FruitUsage object, int id) {
          object.id = id;
        },
        objectToFB: (FruitUsage object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(3, object.usageCount);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final usageCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = FruitUsage(id: idParam, usageCount: usageCountParam);

          return object;
        }),
    Session: obx_int.EntityDefinition<Session>(
        model: _entities[2],
        toOneRelations: (Session object) => [],
        toManyRelations: (Session object) => {},
        getId: (Session object) => object.id,
        setId: (Session object, int id) {
          object.id = id;
        },
        objectToFB: (Session object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          final topicOffset =
              object.topic == null ? null : fbb.writeString(object.topic!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dateOffset);
          fbb.addInt64(2, object.timeSpent);
          fbb.addOffset(4, topicOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final timeSpentParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final topicParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final object = Session(
              id: idParam,
              date: dateParam,
              timeSpent: timeSpentParam,
              topic: topicParam);

          return object;
        }),
    Setting: obx_int.EntityDefinition<Setting>(
        model: _entities[3],
        toOneRelations: (Setting object) => [],
        toManyRelations: (Setting object) => {},
        getId: (Setting object) => object.id,
        setId: (Setting object, int id) {
          object.id = id;
        },
        objectToFB: (Setting object, fb.Builder fbb) {
          final timeOfRestOffset = fbb.writeString(object.timeOfRest);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.star1);
          fbb.addInt64(2, object.star2);
          fbb.addInt64(3, object.star3);
          fbb.addInt64(4, object.doneMinutes);
          fbb.addInt64(6, object.hourOfRest);
          fbb.addOffset(7, timeOfRestOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final star1Param =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final star2Param =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final star3Param =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final hourOfRestParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final timeOfRestParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final doneMinutesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = Setting(
              id: idParam,
              star1: star1Param,
              star2: star2Param,
              star3: star3Param,
              hourOfRest: hourOfRestParam,
              timeOfRest: timeOfRestParam,
              doneMinutes: doneMinutesParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Activity] entity fields to define ObjectBox queries.
class Activity_ {
  /// see [Activity.id]
  static final id =
      obx.QueryIntegerProperty<Activity>(_entities[0].properties[0]);

  /// see [Activity.name]
  static final name =
      obx.QueryStringProperty<Activity>(_entities[0].properties[1]);

  /// see [Activity.timeSpent]
  static final timeSpent =
      obx.QueryIntegerProperty<Activity>(_entities[0].properties[2]);
}

/// [FruitUsage] entity fields to define ObjectBox queries.
class FruitUsage_ {
  /// see [FruitUsage.id]
  static final id =
      obx.QueryIntegerProperty<FruitUsage>(_entities[1].properties[0]);

  /// see [FruitUsage.usageCount]
  static final usageCount =
      obx.QueryIntegerProperty<FruitUsage>(_entities[1].properties[1]);
}

/// [Session] entity fields to define ObjectBox queries.
class Session_ {
  /// see [Session.id]
  static final id =
      obx.QueryIntegerProperty<Session>(_entities[2].properties[0]);

  /// see [Session.date]
  static final date =
      obx.QueryStringProperty<Session>(_entities[2].properties[1]);

  /// see [Session.timeSpent]
  static final timeSpent =
      obx.QueryIntegerProperty<Session>(_entities[2].properties[2]);

  /// see [Session.topic]
  static final topic =
      obx.QueryStringProperty<Session>(_entities[2].properties[3]);
}

/// [Setting] entity fields to define ObjectBox queries.
class Setting_ {
  /// see [Setting.id]
  static final id =
      obx.QueryIntegerProperty<Setting>(_entities[3].properties[0]);

  /// see [Setting.star1]
  static final star1 =
      obx.QueryIntegerProperty<Setting>(_entities[3].properties[1]);

  /// see [Setting.star2]
  static final star2 =
      obx.QueryIntegerProperty<Setting>(_entities[3].properties[2]);

  /// see [Setting.star3]
  static final star3 =
      obx.QueryIntegerProperty<Setting>(_entities[3].properties[3]);

  /// see [Setting.doneMinutes]
  static final doneMinutes =
      obx.QueryIntegerProperty<Setting>(_entities[3].properties[4]);

  /// see [Setting.hourOfRest]
  static final hourOfRest =
      obx.QueryIntegerProperty<Setting>(_entities[3].properties[5]);

  /// see [Setting.timeOfRest]
  static final timeOfRest =
      obx.QueryStringProperty<Setting>(_entities[3].properties[6]);
}
